version: "3"
services:
  adel-nodejs-app:
    container_name: adel-nodejs-app-container
    build:
      context: .
      target: Prod
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ENV-TYPE= Production