version: "3"
services:
  adelappserver:
    container_name: adelappserver-container
    build:
      context: .
      target: Prod
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ENV-TYPE= Production