version: "3"
services:
  adel-nodejs-app:
    container_name: adel-nodejs-app-container
    build:
      context: .
      target: Dev
    ports:
      - "4000:4000"
    volumes: 
      - ./src:/adel-nodejs-app/src:ro
    environment:
      - PORT=4000
      - ENV-TYPE= development